"""Add sequence_id to MealPlanInstance

Revision ID: dbd2183291d7
Revises: 44df98c1fabd
Create Date: 2025-11-09 17:57:47.108199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd2183291d7'
down_revision: Union[str, None] = '44df98c1fabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_instances', sa.Column('sequence_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_meal_plan_instances_sequence_id'), 'meal_plan_instances', ['sequence_id'], unique=False)
    op.create_foreign_key(None, 'meal_plan_instances', 'schedule_sequences', ['sequence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plan_instances', type_='foreignkey')
    op.drop_index(op.f('ix_meal_plan_instances_sequence_id'), table_name='meal_plan_instances')
    op.drop_column('meal_plan_instances', 'sequence_id')
    # ### end Alembic commands ###
