"""initial schema with week templates refactor

Revision ID: 44df98c1fabd
Revises: 
Create Date: 2025-11-06 23:09:45.406388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44df98c1fabd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_week_index', sa.Integer(), nullable=False),
    sa.Column('advancement_day_of_week', sa.Integer(), nullable=False),
    sa.Column('advancement_time', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_bot_token', sa.String(), nullable=True),
    sa.Column('notification_channel_id', sa.String(), nullable=True),
    sa.Column('notification_time', sa.String(), nullable=False),
    sa.Column('notification_timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('discord_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('week_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_template_id', sa.UUID(), nullable=False),
    sa.Column('instance_start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['week_template_id'], ['week_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_instances_instance_start_date'), 'meal_plan_instances', ['instance_start_date'], unique=False)
    op.create_index(op.f('ix_meal_plan_instances_week_template_id'), 'meal_plan_instances', ['week_template_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recipe_type', sa.String(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('postmortem_notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_owner_id'), 'recipes', ['owner_id'], unique=False)
    op.create_table('sequence_week_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('week_template_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['schedule_sequences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_template_id'], ['week_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_week_mappings_sequence_id'), 'sequence_week_mappings', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_week_mappings_week_template_id'), 'sequence_week_mappings', ['week_template_id'], unique=False)
    op.create_table('grocery_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_instance_id', sa.UUID(), nullable=False),
    sa.Column('shopping_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_instance_id'], ['meal_plan_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_meal_plan_instance_id'), 'grocery_lists', ['meal_plan_instance_id'], unique=False)
    op.create_index(op.f('ix_grocery_lists_shopping_date'), 'grocery_lists', ['shopping_date'], unique=False)
    op.create_table('meal_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_instance_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_plan_instance_id'], ['meal_plan_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_assignments_assigned_user_id'), 'meal_assignments', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_meal_assignments_meal_plan_instance_id'), 'meal_assignments', ['meal_plan_instance_id'], unique=False)
    op.create_index(op.f('ix_meal_assignments_recipe_id'), 'meal_assignments', ['recipe_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('CUP', 'TABLESPOON', 'TEASPOON', 'FLUID_OUNCE', 'PINT', 'QUART', 'GALLON', 'ML', 'LITER', 'GRAM', 'KILOGRAM', 'OUNCE', 'POUND', 'COUNT', 'WHOLE', 'ITEM', 'BUNCH', 'CLOVE', 'CAN', 'PINCH', 'DASH', 'TO_TASTE', name='ingredientunit'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('depends_on_step_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['recipe_instructions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_instructions_recipe_id'), 'recipe_instructions', ['recipe_id'], unique=False)
    op.create_table('week_day_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_template_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['week_template_id'], ['week_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_day_assignments_assigned_user_id'), 'week_day_assignments', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_week_day_assignments_recipe_id'), 'week_day_assignments', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_week_day_assignments_week_template_id'), 'week_day_assignments', ['week_template_id'], unique=False)
    op.create_table('grocery_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grocery_list_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source_recipe_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_list_items_grocery_list_id'), 'grocery_list_items', ['grocery_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grocery_list_items_grocery_list_id'), table_name='grocery_list_items')
    op.drop_table('grocery_list_items')
    op.drop_index(op.f('ix_week_day_assignments_week_template_id'), table_name='week_day_assignments')
    op.drop_index(op.f('ix_week_day_assignments_recipe_id'), table_name='week_day_assignments')
    op.drop_index(op.f('ix_week_day_assignments_assigned_user_id'), table_name='week_day_assignments')
    op.drop_table('week_day_assignments')
    op.drop_index(op.f('ix_recipe_instructions_recipe_id'), table_name='recipe_instructions')
    op.drop_table('recipe_instructions')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_assignments_recipe_id'), table_name='meal_assignments')
    op.drop_index(op.f('ix_meal_assignments_meal_plan_instance_id'), table_name='meal_assignments')
    op.drop_index(op.f('ix_meal_assignments_assigned_user_id'), table_name='meal_assignments')
    op.drop_table('meal_assignments')
    op.drop_index(op.f('ix_grocery_lists_shopping_date'), table_name='grocery_lists')
    op.drop_index(op.f('ix_grocery_lists_meal_plan_instance_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index(op.f('ix_sequence_week_mappings_week_template_id'), table_name='sequence_week_mappings')
    op.drop_index(op.f('ix_sequence_week_mappings_sequence_id'), table_name='sequence_week_mappings')
    op.drop_table('sequence_week_mappings')
    op.drop_index(op.f('ix_recipes_owner_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meal_plan_instances_week_template_id'), table_name='meal_plan_instances')
    op.drop_index(op.f('ix_meal_plan_instances_instance_start_date'), table_name='meal_plan_instances')
    op.drop_table('meal_plan_instances')
    op.drop_table('week_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('schedule_sequences')
    # ### end Alembic commands ###
